### ISSUE TITLE
Better description for anonymous types

### ISSUE THREAD

**Issue by iNecas** [pitr-ch/algebrick#8]
```ruby
Envelope = Algebrick.type do
  fields! request_id: Integer,
            sender_id: String,
            receiver_id: type { variants String, AnyExecutor = atom, UnknownWorld = atom },
            message: type { variants Request, Response }
```

With, `Envolope.to_s` it produces `NoName`, where it could descibe, the message as the variant of other types

**Comment by pitr-ch** [comment]
@iNecas  see https://github.com/pitr-ch/algebrick/commit/62b75033a1a6a1132b44d92de9bf5e3098bcb6d9

**Comment by iNecas** [comment]
Nice! I guess we can close this issue now.

**Comment by pitr-ch** [comment]
Reopening to test auto-closing ;)
